# Generated by Django 4.2.5 on 2023-10-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_method', models.CharField(choices=[('Courier', 'Courier'), ('Self-delivery', 'Self-delivery'), ('Post', 'Post')], default='Courier', max_length=16)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('In process', 'In process'), ('Lost', 'Lost')], default='In process', max_length=16)),
                ('delivery_notif_in_time', models.IntegerField(choices=[(24, 24), (6, 6), (1, 1)], default=None, null=True)),
                ('delivery_time', models.DateTimeField()),
                ('payment_methods', models.CharField(choices=[('Card', 'card'), ('Cash', 'Cash'), ('Card online', 'Card online')], default='Card online', max_length=16)),
                ('payment_statuses', models.CharField(choices=[('Paid', 'Paid'), ('In process', 'In process')], default='In process', max_length=16)),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
